[package]
name = "tinf"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = 1

[features]
dhat-heap = []

[dev-dependencies]
dhat = "0.3"

[dependencies]
dhat = "0.3"
prost = "0.14"
prost-types = "0.14"

[build-dependencies]
prost-build = "0.14.1"
